Algoritmo "Media"

Var

nota1, nota2, nota3, media : real
Nome_Aluno: caracter

Inicio

escreva("Digite o nome do Aluno:")
leia (Nome_Aluno)
escreva ("Digite a primeira nota:")
leia (nota1)
escreva ("Digite a segunda nota:")
leia (nota2)
escreva ("Digite a terceira nota:")
leia (nota3)

media:= (nota1 + nota2 + nota3)/3
escreva (nome_Aluno, "Sua media das notas é: ", media)
Fimalgoritmo